// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kznlvpvhpgovjmtpdaxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bmx2cHZocGdvdmptdHBkYXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTUyNjgsImV4cCI6MjA2MjMzMTI2OH0.GSNyw5MhcR6wl98YbH4IANxzW3l8a8aQdJrv3DrOiXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);